name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Changed from 3.12 to 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn  # Added for production

      - name: Create startup file
        run: |
          echo "from app import app
          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=5000)" > startup.py

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}        # FIXED
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}        # FIXED
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # FIXED

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VetchaTheBoss'
          package: .  # ADDED - tells what to deploy
